### ISSUE TITLE
Tracking issues for samples without tutorials/documentation

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/Vulkan-Samples#729]
Esp. older samples don't have proper tutorials/documentation and only contain a readme stub. 

Since we want to make the documentation of this repo part of the broader Vulkan docs, we should add proper tutorials/documentation for all samples.

This is a tracker issue for that, here is the list of tutorials that don't have a proper tutorial/readme:

- [ ] api/compute_nbody
- [ ] api/hpp_compute_nbody
- [ ] api/dynamic_uniform_buffers
- [ ] api/hpp_dynamic_uniform_buffers
- [ ] api/hdr
- [ ] api/hpp_hdr
- [ ] api/hello_triangle
- [ ] api/hpp_hello_triangle
- [ ] api/instancing
- [ ] api/hpp_instancing
- [ ] api/terrain_tessellation
- [ ] api/hpp_terrain_tessellation
- [ ] api/texture_loading
- [ ] api/hpp_texture_loading
- [ ] extensions/conservative_rasterization
- [ ] extensions/fragment_shading_rate
- [ ] extensions/mesh_shading
- [ ] extensions/open_gl_interop
- [ ] extensions/push_descriptors
- [ ] extensions/raytracing_basic
- [ ] extensions/ray_queries
- [ ] extensions/synchronization_2
- [ ] performance/texture_compression_comparison

This is related to https://github.com/KhronosGroup/Vulkan-Samples/issues/693

**Comment by tomadamatkinson** [comment]
We may want to comment up the hello triangle code base with links to the Vulkan Tutorial documentation. It may make it easier if a reader can jump from function X to a specific part of the documentation

**Comment by SaschaWillems** [comment]
We agreed that this has very little priority, esp. when compared to the effort, so closing this.
